In [3]:
import numpy as np
import pandas as pd
import matplotlib as plt

np.random.seed(29)

In [86]:
import scipy.stats as stats

In [87]:
# 1 How likely is it that you roll doubles when rolling two dice?

n_trials = n_rows = 10_000
n_dice = n_cols = 2

rolls = np.random.choice([1,2,3,4,5,6], size = (n_trials, n_dice))
rolls

array([[6, 1],
       [4, 4],
       [6, 3],
       ...,
       [3, 2],
       [1, 2],
       [4, 2]])

array([10, 11,  4, ...,  7,  5, 10])

In [91]:
(rolls[:,0]==rolls[:,1]).mean()

0.1696

In [21]:
#convert to DF
rdf = pd.DataFrame(rolls)
rdf.describe()
#rename columns for ease
rdf = rdf.rename(columns={0: 'D1', 1: 'D2'})

In [33]:
doubles = rdf.D1 - rdf.D2 == 0
doubles.value_counts()

False    8291
True     1709
dtype: int64

In [ ]:
# 2 If you flip 8 coins, what is the probability of getting 
# exactly 3 heads? What is the probability of getting more than 3 heads?

In [81]:
n_trials = n_rows = 10_000
n_qt = n_cols = 8
# 1 = heads
# 2 = tails
flips = np.random.choice([1, 2], size = (n_trials, n_qt))
no_tails = flips % 2
threeheads = no_tails.sum(axis = 1) == 3


In [82]:
threeheads.sum() #percent with only 3 HEADS
2215/10000

0.2215

In [92]:
morethreeheads = no_tails.sum(axis = 1) > 3
(morethreeheads.sum()) / 10000
# 85% have 3 or more heads

0.6338

In [ ]:
# 3

In [43]:
fdf = pd.DataFrame(flips)

fdf.describe()

0      1      2      3      4      5      6      7
count   10000  10000  10000  10000  10000  10000  10000  10000
unique      2      2      2      2      2      2      2      2
top         T      T      T      H      H      T      H      H
freq     5036   5058   5065   5026   5006   5064   5059   5086

In [72]:
no_tails

array([[1, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 1, 0],
       ...,
       [1, 1, 0, ..., 1, 0, 1],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 1, 1, 1]])

3 There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [96]:
n_trials = n_rows = 10_000
n_students = n_cols = 2
#wd = 0, dds = 1
boards = np.random.choice([0,1], size = (n_trials, n_students), p =[0.75, 0.25])
boards

array([[0, 0],
       [1, 0],
       [0, 0],
       ...,
       [0, 1],
       [0, 1],
       [0, 0]])

In [97]:
(boards.sum(axis = 1) ==2).mean()

0.0636

4 Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [100]:
pop = np.random.normal(3,1.5, size = (10000, 5))

In [102]:
(pop.sum(axis=1) < 17).mean()

0.732

In [ ]:
#5

In [103]:
men = np.random.normal(178,8, size = 10000)
women = np.random.normal(170, 6, size = 10000)

In [106]:
(women > men).mean()

0.2096

#6 When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [111]:
# 0 = no issue
# 1 = issue
install = np.random.choice([0,1], size = (10000, 50), p = [249/250, 1/250])

In [113]:
(install.sum(axis = 1) == 0).mean()

0.8182

In [114]:
install_100 = np.random.choice([0,1], size = (10000, 100), p = [249/250, 1/250])

In [115]:
(install_100.sum(axis = 1) == 0).mean()

0.6634

In [116]:
install_150 = np.random.choice([0,1], size = (10000, 150), p = [249/250, 1/250])

In [117]:
(install_150.sum(axis = 1) > 0).mean()

0.4568

In [118]:
install_450 = np.random.choice([0,1], size = (10000, 450), p = [249/250, 1/250])

In [120]:
(install_450.sum(axis = 1) == 0).mean()

0.164

#7 There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

How likely is it that a food truck will show up sometime this week?

In [124]:
#0 = no truck
#1 = truck
trucks = np.random.choice([0,1], size = (10000, 3), p = (0.3, 0.7))

In [134]:
(trucks.sum(axis = 1)>0).mean()

0.9714

In [126]:
trucks1 = np.random.choice([0,1], size = (10000, 2), p = (0.3, 0.7))

In [127]:
(trucks1.sum(axis = 1) > 0).mean()

0.9143

8 If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [132]:
bd = np.random.choice(range(1,366), size = (10000, 23))
bd

array([[218, 100, 316, ..., 210, 314,  82],
       [284, 196, 361, ..., 294, 285, 212],
       [ 31,  39,  17, ..., 249, 130, 281],
       ...,
       [218, 152, 177, ...,  73, 246,  30],
       [ 68, 251, 114, ...,  76, 293, 130],
       [ 36, 280, 357, ..., 175, 365, 296]])

In [133]:
(pd.DataFrame(bd).nunique(axis = 1) < 23).mean()

0.5098